### ISSUE TITLE
Intsalling on Mac

### ISSUE THREAD

**Issue by nunonog** [wavexx/tblutils#1]
Hello,
I was just trying to get tblutils installed on my MaC, and the error when running **make install**:
>
_install: illegal option -- t_

Seems there's an incompatibility with the MaC install?

Thanks in advance
BW

**Comment by wavexx** [comment]
I don't own a mac, but my guess is that it just needs different flags for the "install" command.

Can you try the current sources? I've used an alternative syntax.

**Comment by nunonog** [comment]
Thanks it did work, I tried removing the '-t' flag only but didn't work.
It works now

**Comment by wavexx** [comment]
Ok, closing then
